### ISSUE TITLE
Launcher: text not visible in selection

### ISSUE THREAD

**Issue by coxackie** [pop-os/shell#132]
This is using default Adwaita:
![Screenshot from 2020-03-31 09-42-51](https://user-images.githubusercontent.com/22049642/78005882-1e2d4b80-7334-11ea-82e5-01d546834d78.png)
It appears that launcher works well with light shell themes, but text becomes invisible in dark variants.

**Comment by mmstick** [comment]
@isantop I think our chosen font color isn't very compatible with Adwaita's dark theme.

**Comment by isantop** [comment]
I think I can fix that by simply removing the text color from the stylesheet, but we should caution that Pop Shell will not look good with any theme other than Pop.

**Comment by coxackie** [comment]
@isantop I understand that the priority for you guys is Pop, but it would be a great advertisement of the work that you do if you try to respect the shell theme, in order to be used widely. After all, you yourselves mention that you would like to propose this for upstream. A little extra thought here could take you a long way...

**Comment by coxackie** [comment]
by the way, this is with Pop-dark theme:

![Screenshot from 2020-04-01 16-15-54](https://user-images.githubusercontent.com/22049642/78154449-308eae80-7434-11ea-9983-4e6fc18a3de9.png)

same issue, clearly.

**Comment by mmstick** [comment]
Not at all what I'm seeing

![Screenshot from 2020-04-01 10-19-27](https://user-images.githubusercontent.com/4143535/78161186-4daa8980-7402-11ea-98ff-d80e0afa5727.png)

**Comment by isantop** [comment]
@mmstick If a user sets the Pop-dark theme from tweak tool, then it will still use the light-mode stylesheet, producing this issue.

**Comment by coxackie** [comment]
@isantop this is exactly right. By the way, a bit off-topic (but related to the theme and `gnome-tweaks`), installing using deb files the latest 5.1.2 version of pop gtk-theme, only `Pop-dark` appears as an option in "Shell" at `gnome-tweaks`, the lighter `Pop` does not appear (but does appear in Applications, etc.) User of Arch linux, as I mentioned, and I have cross-validated this issue with the AUR package maintainer. Can you also see the issue in your local builds?

**Comment by isantop** [comment]
That's something I'm aware of and is a side-effect of the current implementation of the build system. It's somewhat low-priority right now while we work towards the 20.04 release.

**Comment by coxackie** [comment]
no problem - as long as it is going to be fixed, it indeed does not feel like a priority. I mean, as long as it gets dealt with in time. You want people outside `Pop!_OS` to be able to use the themes, I hope.

**Comment by evanleck** [comment]
FWIW I just started having this issue as well. I installed `arc-theme` and a set of icons, tried them out for a bit, and switched back to Pop but now my launcher looks like this with the light theme:

![Launcher Color](https://user-images.githubusercontent.com/21947/86817642-220af100-c03a-11ea-9b2d-ee35632050bc.png)

It looks fine with the dark theme and I've tried changing the theme both in tweaks and the appearance settings.

**Comment by GaryBer** [comment]
It was happening to me as well but rebuilding using `./rebuild.sh` a few days later fixed it.
![image](https://user-images.githubusercontent.com/34002641/94516980-a493ee80-01ec-11eb-90bc-bf176ce56a8a.png)

**Comment by GaryBer** [comment]
Changing themes seems to cause the issue then doing `ALT+F2` then `r` caused the problem to happen again. Switching back to the same theme did not fix it.
![image](https://user-images.githubusercontent.com/34002641/94580468-9622f280-023f-11eb-8fbc-677b8256f052.png)

**Comment by ptrm** [comment]
A workaround to make it work on dark themes with bright menus (like Ubuntu's Yaru mentioned above) is to force the choice of light style somehow, e.g.:
```
$ cp light.css dark.css
$ make local-install
```

**Comment by tobz1000** [comment]
I've just experienced this issue, not long after a fresh OS install.

I switched to light mode and the colours were initially legible in the launcher. The only noteworthy things I can think of after that were installing some system updates, and rebooting. After reboot:

![Screenshot from 2021-07-01 20-28-31](https://user-images.githubusercontent.com/1471978/124179642-069ac080-daab-11eb-8e57-078e25190d1e.png)

I also have gnome-tweak installed, but I don't think I'd touched any theme settings.

**Comment by rmerren** [comment]
Thanks to all those who responded. I have not installed any themes or used gnome tweak to change themes--I was using the Light theme as chosen from Desktop->Appearance->Light straight out of the box (though I have upgraded this laptop through several versions). I switched it to Dark and now the text is visible. I hope this is addressed at some point, but (as some mentioned above) it is not a showstopper at all and easily worked around.

**Comment by aidenlangley** [comment]
This is now fixed for me - on `master`, latest commit is `1fddaa8953a6554a83038bb5662662eb761eb361`. It's not immediately obvious to me how though. Commits between metadata version bump & now don't seem relevant to this issue.

![Screenshot from 2021-10-31 03-39-52](https://user-images.githubusercontent.com/684721/139537804-9376a0f4-6e16-40b1-a0db-37f2337360d3.png)

**Comment by mmstick** [comment]
Could have been the change made for improving high contrast support.

**Comment by Guztaver** [comment]
> Edit: I have recently removed tweak tools from my system.

So, i had been having this problem to 1 month, and i solved now. I download the "User Theme" Extension for Gnome-Tweak an change the Shell theme to "Pop Dark", and solved the problem.

So, the bug is that gnome tweaks doesn't change the "shell" theme.

![2021-12-08_18-54](https://user-images.githubusercontent.com/39814943/145290745-bffc8a94-dd2f-4b3d-a4b2-ea5602024dc6.png)

**Comment by mds08011** [comment]
To expand on @Guztaver 's solution, after downloading [User Theme](https://extensions.gnome.org/extension/19/user-themes/) Gnome Extension, I saw the following in the Gnome Tweaks "appearance" section.

This is what I saw with the "default" shell theme.
<img src="https://user-images.githubusercontent.com/8010709/147868246-056f6c4d-b9e7-4a88-ba20-cacfbe1248b9.png" width="90%">

This is what I saw with after changing to the "pop dark" shell theme.
<img src="https://user-images.githubusercontent.com/8010709/147868256-e668b1fc-d78f-4fd7-bcf7-610d31b8ea74.png" width="90%">

**Comment by tobz1000** [comment]
Switching via the "User Themes" extension has... changed the issue for me.

The "User Themes" UI only seems to change the colours of gnome-shell specific modals, e.g. the "Applications" menu, and the launcher. Below you can see that the launcher is dark, but my windows are still light. The text is at least readable now!

![Screenshot from 2022-01-19 12-12-53](https://user-images.githubusercontent.com/1471978/150127912-e735b954-a0ad-4d88-bc9e-523e2c95802f.png)

But now, the regular theme configuration panel under Settings -> Desktop -> Apperance seems to not control gnome-shell modals at all, only normal windows. Here I have dark mode set, but a light-theme modal:

![Screenshot from 2022-01-19 12-16-24](https://user-images.githubusercontent.com/1471978/150127995-dff16315-21a2-4b50-acdc-2fcbb7c1bc48.png)

This is fairly frustrating for me because I change between light and dark theme often, depending on my environment.

**Comment by Anarbb** [comment]
If you still having this issue, a solution that worked for me, is enabling the User Themes extension and selecting Pop-dark

**Comment by Guekka** [comment]
Still a relevant issue. This is unfortunate, as pop-shell is great but this makes it very hard to use for me
Using the default Gnome theme with no customization

**Comment by HazemKaroui** [comment]
Fixed this on Fedora by going to **Tweaks->Appearance** and changing **Legacy Applications** from Adwaita to **Adwaita-dark**.
Only side effect is that all GTK3 apps turned to dark mode now.

**Comment by drscotthawley** [comment]
OMG so glad I found this thread! I have been just tolerating this issue for the longest time -- i.e. barely being able to read text, all GUI elements (sliders, radio buttons etc) being invisible and just having to guess at their locations.
Downloaded the Tweak Tools and the [User Themes](https://extensions.gnome.org/extension/19/user-themes/) and set the Shell to Pop-dark, [restarted gnome](https://askubuntu.com/questions/214856/how-to-reload-gnome-shell-theme-via-a-command), and I can finally read the menus properly! 
:partying_face:

**Comment by ghost** [comment]
Setting the shell theme to Pop Dark does indeed fix the issue for the launcher, but it is starting to create issues on newer versions of GNOME, mainly in the quick settings panel. Im curious if anyone has found just some simple css to override the highlighted text color for whatever theme you are using? 
w/Pop-Dark
![image](https://github.com/pop-os/shell/assets/114200916/e13a3f74-5a55-4151-bc9e-79131f891a7b)
w/ Adwaita
![gnome-shell-screenshot-78w0qg](https://github.com/pop-os/shell/assets/114200916/9e90b5fb-cede-4cb0-aba9-a4c9a2e950ce)
This is on an arch install (boy i can't wait for COSMIC so i dont have to deal with GNOME anymore)

Edit: after a [bit more sleuthing](https://www.reddit.com/r/pop_os/comments/pvveho/comment/hee7l4q/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) i was able to find a solution

i couldnt get it to take a local css override on the system, but as the comment says you can edit the text color on the system by modifying `/usr/share/gnome-shell/extensions/pop-shell@system76.com/light.css` as sudo, and change color `.pop-shell-search-element:select{ color: #393634; }` from `#393634` to `#beeef7` (as just one example, use what you like)

**Comment by nbuckley** [comment]
FYI, I am still seeing the issue pointed out by the OP, although it visually it looks more like the issue pointed out by mds08011 on [Jan 2 2022](https://github.com/pop-os/shell/issues/132#issuecomment-1003671686) where the text is still technically visible, it's just difficult to see because of lack of contrast (grey text on grey bg).

This occurred with a clean installation of Pop!_OS — all I did was set the mode to Dark in Settings/Appearance.
