### ISSUE TITLE
Gnome Shell freezes regularly after updating to 22.04

### ISSUE THREAD

**Issue by joelostblom** [pop-os/shell#1462]
**(1) Issue/Bug Description:**

I am seeing the issue reported here https://www.reddit.com/r/pop_os/comments/v389gi/hello_friends_my_pop_os_2204_is_freezing_after_a/ (and given the number of upvotes many users seem to be affected). In brief, PopOS Gnome Shell occasionally freezes and has to be rebooted via Ctrl + Alt + F3, log in through the terminal, run `sudo killall -1 gnome-shell`, and then switch back to the graphical login using Ctrl + Alt + F2. This happens every few minutes and is quite annoying, especially as I am on a Lemur Pro, which I would expect to be compatible and tested with PopOS. The issue seemingly only occurs when an external monitor is connected (I believe) and I see this message in the journalctl log: `Window manager warning: Overwriting existing binding of keysym 6f`, same as what was posted by another reddit user.

**(2) Steps to reproduce (if you know):**

Connect an external monitor and wait?

**(3) Expected behavior:**

No freeze

**(4) Distribution (run `cat /etc/os-release`):**

22.04
 

**(5) Gnome Shell version:**

GNOME Shell 42.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1653580316~22.04~42102e9
  Candidate: 1.1.0~1653677645~22.04~44ca2cd
```

**(7) Where was Pop Shell installed from:**

I am running PoPOS, installed by system76 on my lemur pro.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

One external UltraWide

**(9) Other Installed/Enabled Extensions:**

Battery time, edge gap, hide top bar, weekstarts on monday

**(10) Other Notes:**

**Comment by mmstick** [comment]
Try updating the system and restarting

**Comment by Xanewok** [comment]
I can reproduce that on on Ubuntu 22.04 (Shell 42.1), I have a single 16:9 display connected at all times, only have the Pop Shell extension installed and the built-in Ubuntu AppIndicators and UbuntuDock.

1. Initially had installed af192b49bac58d0204167ab690fa80d7ac524071 (no freezes)
2. Updated to 42102e9 but had the hangs as described in https://github.com/pop-os/gnome-shell/issues/112
3. Updated to 44ca2cd to fix the issue but now I have weird partial hangs where the shell starts having freeze periods (after which it's almost unusable so I need to restart the system)

**Comment by mmstick** [comment]
Maybe it needs https://github.com/pop-os/gnome-shell/pull/110

**Comment by joelostblom** [comment]
Installing all new updates as of yesterday and restarting does seem to have fixed this for me. One day without issues while connected to an external monitor (and this issue used to occur every hour)

**Comment by dfontana** [comment]
Is there any other solutions to this? I have an updated system but experience this daily, sometimes multiple times. It happens frequently when launching intensive applications (games) that take control of the full screen or consume a large allocation of RAM. Albeit that may be more coincidence than much else. Below are the only logs I can see

<details>
<summary>journalctl SYSLOG_IDENTIFIER=gnome-shell -xe</summary> 

```
Sep 21 20:17:42 pop-os gnome-shell[2689]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x62000>
Sep 21 20:18:53 pop-os gnome-shell[3960]: [2022-09-22T00:18:53Z ERROR viaduct::backend::ffi] Missing HTTP status
Sep 21 20:18:53 pop-os gnome-shell[3960]: [2022-09-22T00:18:53Z ERROR viaduct::backend::ffi] Missing HTTP status
Sep 21 20:19:38 pop-os gnome-shell[2689]: Window manager warning: Window 0x7000003 sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.
```

</details>

My uname -a: `Linux pop-os 5.19.0-76051900-generic #202207312230~1660780566~22.04~9d60db1 SMP PREEMPT_DYNAMIC Thu A x86_64 x86_64 x86_64 GNU/Linux`

**Comment by pinduzera** [comment]
Same happens Here. Usually when alt-tabbing, it randomly freezes while everything is working, discord games looks to be running, but the UI is simply unresponsive. This have been happening for a while to me, even after updating.

uname -a: Linux pop-os 5.19.0-76051900-generic #202207312230~1663791054~22.04~28340d4 SMP PREEMPT_DYNAMIC Wed S x86_64 x86_64 x86_64 GNU/Linux

**Comment by BarbzYHOOL** [comment]
same here, all the time

**Comment by Dfred** [comment]
Likewise on v42.5 (Ubuntu 22.04.1) and this happens more as the process gets older. Freezes can last from 3 to at least 30s. Restarting the gnome-shell process solves the problem for some time before it becomes obvious again.

**Comment by jvbs** [comment]
Same here, it freezes frequently for 30s~1min then works fine again, pretty annoying tbh

**Comment by adamsimonini** [comment]
I have this issue as well. Process and applications that increase freezing: locking the screen and unlocking the screen by signing in, and VSCode. I'm on 22.04.

**Comment by rezarajan** [comment]
I've been experiencing this issue as well. From what I can tell, the screen freezes when running any hardware-accelerated applications (Discord, watching a video on Firefox/Brave). Console generally works if I press `Ctrl`+`Alt`+`F3`, but sometimes it's a full system freeze and I can't do anything. In the case of the former, I can follow the resolution outlined in [this Reddit comment ](https://www.reddit.com/r/pop_os/comments/o6ak72/comment/hug75me/?utm_source=share&utm_medium=web2x&context=3) to get back into a functioning GUI, but otherwise I need to force a reboot.

This behavior has been exhibited on two different machines.

---

**Pop!_OS Version:** 22.04 (NVIDIA)
**Hardware:** 
- (Laptop) Intel Core i9 11900H + NVIDIA RTX 3060
- (Desktop) AMD Ryzen 9 7900X + NVIDIA RTX 4070

**Comment by mmstick** [comment]
@rezarajan This is usually caused by critical errors in the graphics driver. You can watch kernel logs with `sudo dmesg -wH` / `journalctl -fk` to see the exact errors being emitted. Disabling hardware acceleration may be the only option besides kernel and driver updates.

**Comment by janban-outlook** [comment]
Same issue here on Pop!_OS 22.04 on two different laptops. I have always a second screen connected, so can't say if that is a condition for this freeze to happen. I have the feeling that it always happens when I am in a browser window, on the first laptop I work with Firefox, on the other with Chrome. Suddenly scrolling does not work anymore and everything is frozen. However, the mouse pointer works and changes when hovering over window borders for example.
I can always solve the issue by going to another TTY and pkill gnome-shell.
When I look at htop in the other tty session, then three processes are taking all cpu power: system-journald, rsyslogd, and gnome-shell.

journalctl SYSLOG_IDENTIFIER=gnome-shell -xe:
```
Window manager warning: last_focus_time (8187498) is greater than comparison timestamp (8187497).  This most likely represents a buggy client sending inaccurate timestamps in messages s>
Window manager warning: last_user_time (8187498) is greater than comparison timestamp (8187497).  This most likely represents a buggy client sending inaccurate timestamps in messages su>
Window manager warning: 0x6800003 appears to be one of the offending windows with a timestamp of 8187498.  Working around...
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2c0000f
```

**Comment by GlenCooper** [comment]
I too am experiencing this freezing issue on my Ubuntu 22.04.2 laptop.  When it happens I am still able to ssh into the laptop from another host on my LAN.  Every time it's gnome-shell that is at 100% CPU.  I've found that when I kill -9 the PID of the gnome-shell process with the highest CPU %, it clears everything on my desktop and returns to the login screen to start anew.

I thought maybe it was gnome animations somehow causing it since I noticed that the freeze happened when I moved my mouse cursor to the upper left-hand corner of my main screen, and that's where the "Activities" button does it's fancy animation thing when hovered.  Nope.  Animations turned off.  Still happens.

However, I have narrowed it down to moving my mouse cursor in such a way that it hits a particular spot on my main monitor.  The upper-left corner of it.  Unsure what to do about it, so I'll just try my best to avoid mousing over that bad spot for now.

Here is how my Displays are set currently.  The freeze occurs when I move the cursor to the upper-left corn or Screen 3:
![Screenshot from 2023-08-03 10-03-58](https://github.com/pop-os/shell/assets/967793/4ea61618-e3eb-456e-9b14-5e0de5f1aaac)

**Comment by GlenCooper** [comment]
Happening to me as well on Ubuntu 22.04.  I run POP!_OS as well, so happened to see this thread.
So at least you now know it's not just on POP!_OS.

**Comment by GlenCooper** [comment]
Happening to me as well on Ubuntu 22.04. I run POP!_OS as well on a different laptop so I just happened to see this thread.
So at least you now know it's not just on POP!_OS.
I've noticed that it freezes instantly when I move my mouse cursor the top left-hand corner of one of my 5 displays.  For now, just staying away that broken corner.

UPDATE:
I came up with a workaround that has stopped this issue from happening.  I have multiple displays, positioned like this: https://ibb.co/ZLtXBPs
Previously when the lockups were happening, my Primary Display was set to # 5.  It was the upper lefthand corner of that display that was upon mouseover was causing the lock-ups.  I changed my Primary Display designation to be # 2, that way the upper left-hand corner of that display was much less likely to experience accidental mouseover and subsequent lock-ups.

**Comment by mmstick** [comment]
Try disabling animations from the accessibility settings panel

**Comment by GlenCooper** [comment]
> Try disabling animations from the accessibility settings panel

Good suggestion.  Tried that.  Still seeing same behavior.

**Comment by x51don** [comment]
I have this same, as a workaround I switched to hybrid graphics, and it is working so far: 
sudo system76-power graphics hybrid

edit: found a even better workaround which is working stable. I set permanently Nvidia to Maximum Performance and Hybrid graphics. Funny thing is, that it is not drawing any more power, and switching between internal and Nvidia GPU without problems.

https://rastating.github.io/how-to-permanently-set-nvidia-powermizer-settings-in-ubuntu/

**Comment by DanielJoyce** [comment]
Been biting me too now. Always happens in chrome.

**Comment by DanielJoyce** [comment]
Found in dmesg:

```
Dec 09 11:57:33 pop-os kernel: NVRM: GPU at PCI:0000:01:00: GPU-61087b93-bcbe-0a03-89cc-aa22818b9325
Dec 09 11:57:33 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 109, pid=4098, name=chrome, Ch 0000000e, errorString CTX SWITCH TIMEOUT, Info 0xe4009
Dec 09 11:57:33 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 62, pid=4098, name=chrome, 000120c2 0001211d 00011b54 00015a81 00015e8c 00013ee1 00000011 00000000
Dec 09 11:57:33 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 45, pid=4098, name=chrome, Ch 00000008
Dec 09 11:57:33 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 45, pid=4098, name=chrome, Ch 0000000e
Dec 09 11:57:33 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 45, pid=4098, name=chrome, Ch 0000000f
Dec 09 11:57:33 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 45, pid=4098, name=chrome, Ch 00000010
Dec 09 11:57:33 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 45, pid=4098, name=chrome, Ch 00000011
Dec 09 11:57:33 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 45, pid=4098, name=chrome, Ch 00000012
Dec 09 11:57:33 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 45, pid=4098, name=chrome, Ch 00000013
Dec 09 11:57:34 pop-os kernel: sched: RT throttling activated
Dec 09 11:57:39 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 109, pid=3364, name=Xorg, Ch 00000018, errorString CTX SWITCH TIMEOUT, Info 0x44009
Dec 09 11:57:44 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 109, pid=609, name=systemd-udevd, Ch 00000002, errorString CTX SWITCH TIMEOUT, Info 0x24009
Dec 09 11:57:45 pop-os kernel: nvidia-modeset: WARNING: GPU:0: AU Optronics Corporation (DP-2): G-SYNC Compatible: EDID min refresh rate invalid, disabling G-SYNC Compa>
Dec 09 11:57:46 pop-os kernel: nvidia-modeset: WARNING: GPU:0: AU Optronics Corporation (DP-2): G-SYNC Compatible: EDID min refresh rate invalid, disabling G-SYNC Compa>
Dec 09 11:57:46 pop-os kernel: wlp0s20f3: deauthenticating from f0:72:ea:80:24:4d by local choice (Reason: 3=DEAUTH_LEAVING)
Dec 09 11:57:51 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 109, pid=3469, name=gnome-shell, Ch 00000020, errorString CTX SWITCH TIMEOUT, Info 0x94009
Dec 09 11:57:51 pop-os kernel: rfkill: input handler enabled
Dec 09 11:57:52 pop-os kernel: nvidia-modeset: WARNING: GPU:0: AU Optronics Corporation (DP-2): G-SYNC Compatible: EDID min refresh rate invalid, disabling G-SYNC Compa>
Dec 09 11:58:00 pop-os kernel: ------------[ cut here ]------------
Dec 09 11:58:00 pop-os kernel: WARNING: CPU: 5 PID: 136484 at /var/lib/dkms/nvidia/545.29.02/build/nvidia/nv.c:4300 nv_set_system_power_state+0x402/0x460 [nvidia]
Dec 09 11:58:00 pop-os kernel: Modules linked in: tls rfcomm xt_nat xt_tcpudp veth xt_conntrack nft_chain_nat xt_MASQUERADE nf_nat nf_conntrack_netlink nf_conntrack nf_>
Dec 09 11:58:00 pop-os kernel:  intel_rapl_msr nvidia(POE) btusb snd_pcm_dmaengine mac80211 rmi_smbus btrtl snd_hda_codec_hdmi input_leds thinkpad_acpi processor_therma>
Dec 09 11:57:33 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 45, pid=4098, name=chrome, Ch 00000013
Dec 09 11:57:34 pop-os kernel: sched: RT throttling activated
Dec 09 11:57:39 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 109, pid=3364, name=Xorg, Ch 00000018, errorString CTX SWITCH TIMEOUT, Info 0x44009
Dec 09 11:57:44 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 109, pid=609, name=systemd-udevd, Ch 00000002, errorString CTX SWITCH TIMEOUT, Info 0x24009
Dec 09 11:57:45 pop-os kernel: nvidia-modeset: WARNING: GPU:0: AU Optronics Corporation (DP-2): G-SYNC Compatible: EDID min refresh rate invalid, disabling G-SYNC Compa>
Dec 09 11:57:46 pop-os kernel: nvidia-modeset: WARNING: GPU:0: AU Optronics Corporation (DP-2): G-SYNC Compatible: EDID min refresh rate invalid, disabling G-SYNC Compa>
Dec 09 11:57:46 pop-os kernel: wlp0s20f3: deauthenticating from f0:72:ea:80:24:4d by local choice (Reason: 3=DEAUTH_LEAVING)
Dec 09 11:57:51 pop-os kernel: NVRM: Xid (PCI:0000:01:00): 109, pid=3469, name=gnome-shell, Ch 00000020, errorString CTX SWITCH TIMEOUT, Info 0x94009
Dec 09 11:57:51 pop-os kernel: rfkill: input handler enabled
Dec 09 11:57:52 pop-os kernel: nvidia-modeset: WARNING: GPU:0: AU Optronics Corporation (DP-2): G-SYNC Compatible: EDID min refresh rate invalid, disabling G-SYNC Compa>
Dec 09 11:58:00 pop-os kernel: ------------[ cut here ]------------
Dec 09 11:58:00 pop-os kernel: WARNING: CPU: 5 PID: 136484 at /var/lib/dkms/nvidia/545.29.02/build/nvidia/nv.c:4300 nv_set_system_power_state+0x402/0x460 [nvidia]
Dec 09 11:58:00 pop-os kernel: Modules linked in: tls rfcomm xt_nat xt_tcpudp veth xt_conntrack nft_chain_nat xt_MASQUERADE nf_nat nf_conntrack_netlink nf_conntrack nf_>
Dec 09 11:58:00 pop-os kernel:  intel_rapl_msr nvidia(POE) btusb snd_pcm_dmaengine mac80211 rmi_smbus btrtl snd_hda_codec_hdmi input_leds thinkpad_acpi processor_therma>
Dec 09 11:58:00 pop-os kernel:  mac_hid acpi_pad sch_fq_codel kyber_iosched msr parport_pc ppdev lp parport drm ramoops reed_solomon pstore_blk pstore_zone efi_pstore i>
Dec 09 11:58:00 pop-os kernel: CPU: 5 PID: 136484 Comm: nvidia-sleep.sh Tainted: P           OE      6.5.6-76060506-generic #202310061235~1697396945~22.04~9283e32
Dec 09 11:58:00 pop-os kernel: Hardware name: LENOVO 20TKCTO1WW/20TKCTO1WW, BIOS N2VET45W (1.30 ) 08/29/2023
Dec 09 11:58:00 pop-os kernel: RIP: 0010:nv_set_system_power_state+0x402/0x460 [nvidia]
Dec 09 11:58:00 pop-os kernel: Code: 75 0e eb 3f 4d 8b ad 60 06 00 00 4d 85 ed 74 33 49 8b bd c8 02 00 00 ba 01 00 00 00 89 de e8 25 c6 ff ff 41 89 c4 85 c0 74 da <0f> >
Dec 09 11:58:00 pop-os kernel: RSP: 0018:ffffb8318164fc98 EFLAGS: 00010206
Dec 09 11:58:00 pop-os kernel: RAX: 000000000000ffff RBX: 0000000000000001 RCX: 0000000000000000
Dec 09 11:58:00 pop-os kernel: RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
Dec 09 11:58:00 pop-os kernel: RBP: ffffb8318164fcd0 R08: 0000000000000000 R09: 0000000000000000
Dec 09 11:58:00 pop-os kernel: R10: 0000000000000000 R11: 0000000000000000 R12: 000000000000ffff
Dec 09 11:58:00 pop-os kernel: R13: ffff9b91564e8000 R14: ffff9b91564e8638 R15: ffff9b9499070000
Dec 09 11:58:00 pop-os kernel: FS:  00007fa2f678b740(0000) GS:ffff9b9861b40000(0000) knlGS:0000000000000000
Dec 09 11:58:00 pop-os kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Dec 09 11:58:00 pop-os kernel: CR2: 00007fbc84005da0 CR3: 000000028c282006 CR4: 00000000007706e0
Dec 09 11:58:00 pop-os kernel: PKRU: 55555554
Dec 09 11:58:00 pop-os kernel: Call Trace:
Dec 09 11:58:00 pop-os kernel:  <TASK>
Dec 09 11:58:00 pop-os kernel:  ? show_regs+0x6d/0x80
Dec 09 11:58:00 pop-os kernel:  ? __warn+0x89/0x160
Dec 09 11:58:00 pop-os kernel:  ? nv_set_system_power_state+0x402/0x460 [nvidia]
Dec 09 11:58:00 pop-os kernel:  ? report_bug+0x17e/0x1b0
Dec 09 11:58:00 pop-os kernel:  ? handle_bug+0x46/0x90
Dec 09 11:58:00 pop-os kernel:  ? exc_invalid_op+0x18/0x80
Dec 09 11:58:00 pop-os kernel:  ? asm_exc_invalid_op+0x1b/0x20
Dec 09 11:58:00 pop-os kernel:  ? nv_set_system_power_state+0x402/0x460 [nvidia]
Dec 09 11:58:00 pop-os kernel:  ? nv_set_system_power_state+0x3fb/0x460 [nvidia]
Dec 09 11:58:00 pop-os kernel:  nv_procfs_write_suspend+0x106/0x1c0 [nvidia]
Dec 09 11:58:00 pop-os kernel:  proc_reg_write+0x69/0xb0
Dec 09 11:58:00 pop-os kernel:  vfs_write+0xff/0x440
Dec 09 11:58:00 pop-os kernel:  ksys_write+0x73/0x100
Dec 09 11:58:00 pop-os kernel:  __x64_sys_write+0x19/0x30
Dec 09 11:58:00 pop-os kernel:  do_syscall_64+0x58/0x90
Dec 09 11:58:00 pop-os kernel:  ? exit_to_user_mode_prepare+0x30/0xb0
Dec 09 11:58:00 pop-os kernel:  ? syscall_exit_to_user_mode+0x37/0x60
Dec 09 11:58:00 pop-os kernel:  ? do_syscall_64+0x67/0x90
Dec 09 11:58:00 pop-os kernel:  ? do_user_addr_fault+0x238/0x6b0
Dec 09 11:58:00 pop-os kernel:  ? exit_to_user_mode_prepare+0x30/0xb0
Dec 09 11:58:00 pop-os kernel:  ? irqentry_exit_to_user_mode+0x17/0x20
Dec 09 11:58:00 pop-os kernel:  ? irqentry_exit+0x43/0x50
Dec 09 11:58:00 pop-os kernel:  ? exc_page_fault+0x94/0x1b0
Dec 09 11:58:00 pop-os kernel:  entry_SYSCALL_64_after_hwframe+0x6e/0xd8
Dec 09 11:58:00 pop-os kernel: RIP: 0033:0x7fa2f6514a77
Dec 09 11:58:00 pop-os kernel: Code: 10 00 f7 d8 64 89 02 48 c7 c0 ff ff ff ff eb b7 0f 1f 00 f3 0f 1e fa 64 8b 04 25 18 00 00 00 85 c0 75 10 b8 01 00 00 00 0f 05 <48> >
Dec 09 11:58:00 pop-os kernel: RSP: 002b:00007ffe95de2418 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
Dec 09 11:58:00 pop-os kernel: RAX: ffffffffffffffda RBX: 0000000000000008 RCX: 00007fa2f6514a77
Dec 09 11:58:00 pop-os kernel: RDX: 0000000000000008 RSI: 00005647cac478f0 RDI: 0000000000000001
Dec 09 11:58:00 pop-os kernel: RBP: 00005647cac478f0 R08: 0000000000000000 R09: 00005647cac478f0
Dec 09 11:58:00 pop-os kernel: R10: 00007fa2f6619cf0 R11: 0000000000000246 R12: 0000000000000008
Dec 09 11:58:00 pop-os kernel: R13: 00007fa2f661a780 R14: 00007fa2f6616600 R15: 00007fa2f6615a00
Dec 09 11:58:00 pop-os kernel:  </TASK>
Dec 09 11:58:00 pop-os kernel: ---[ end trace 0000000000000000 ]---

```

**Comment by DanielJoyce** [comment]
Ahhh, nvidia and their buggy drivers.

**Comment by BarbzYHOOL** [comment]
maybe it will all be fixed in 2028

**Comment by hotpocket** [comment]
Hi Everyone, Not sure if this is the right place for this, maybe someone can direct me if not.  I have been plugging in my pixel 6 pro just to charge, not allowing usb access, but gnome will freeze SOMETIMES ... I know this is the issue because when I unplug my pixel 6 pro the system magically wakes up like nothing is wrong.  Here is the most recent logs from /var/log/syslog  ... maybe this will mean someone to someone but it isn't obvious to me.   

```
Feb  7 11:15:52 LinuxBeast kernel: [ 4047.243929] usb 3-2.1: new high-speed USB device number 6 using xhci_hcd
Feb  7 11:15:52 LinuxBeast kernel: [ 4047.370620] usb 3-2.1: New USB device found, idVendor=18d1, idProduct=4ee1, bcdDevice= 5.10
Feb  7 11:15:52 LinuxBeast kernel: [ 4047.370638] usb 3-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Feb  7 11:15:52 LinuxBeast kernel: [ 4047.370647] usb 3-2.1: Product: Pixel 6 Pro
Feb  7 11:15:52 LinuxBeast kernel: [ 4047.370653] usb 3-2.1: Manufacturer: Google
Feb  7 11:15:52 LinuxBeast kernel: [ 4047.370658] usb 3-2.1: SerialNumber: SerialNumberHere
Feb  7 11:15:52 LinuxBeast systemd-udevd[10224]: 3-2.1: Process '/usr/lib/snapd/snap-device-helper bind snap_cups_cupsd /devices/pci0000:00/0000:00:1c.4/0000:06:00.0/0000:07:02.0/0000:3c:00.0/usb3/3-2/3-2.1 189:261' failed with exit code
 1.
Feb  7 11:15:52 LinuxBeast systemd-udevd[10224]: 3-2.1: Process '/usr/lib/snapd/snap-device-helper bind snap_cups_ippeveprinter /devices/pci0000:00/0000:00:1c.4/0000:06:00.0/0000:07:02.0/0000:3c:00.0/usb3/3-2/3-2.1 189:261' failed with e
xit code 1.
Feb  7 11:15:52 LinuxBeast gnome-shell[4704]: The peer-to-peer connection failed: The name :1.125 was not provided by any .service files. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd pr
ivileges.
Feb  7 11:15:52 LinuxBeast gnome-shell[4704]: JS ERROR: Impossible to update icon for location:mtp://Google_Pixel_6_Pro_SerialNumberHere/: Gio.DBusError: The name :1.125 was not provided by any .service files#012_promisify/proto[asyncFunc]
/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:425:45#012### Promise created here: ####012_queryLocationIcons@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:248:40#012_updateLocationIcon@/usr/share/gn
ome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:283:38#012_update@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:450:14#012updateAndMonitor@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/location
s.js:344:18#012_init@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:347:9#012LocationAppInfo@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:95:4#012MountableVolumeAppInfo@/usr/share/gnome-she
ll/extensions/ubuntu-dock@ubuntu.com/locations.js:334:1#012_onVolumeAdded@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1212:25#012DashToDock_Removables/<@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/l
ocations.js:1154:33
Feb  7 11:15:52 LinuxBeast gvfsd[10249]: Error 1: Get Storage information failed.
Feb  7 11:15:52 LinuxBeast gnome-shell[4704]: The peer-to-peer connection failed: Cache invalid, retry (internally handled). Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
Feb  7 11:15:52 LinuxBeast dbus-daemon[4357]: [session uid=1000 pid=4357] Activating service name='org.gnome.Shell.HotplugSniffer' requested by ':1.45' (uid=1000 pid=4704 comm="/usr/bin/gnome-shell " label="unconfined")
Feb  7 11:15:52 LinuxBeast dbus-daemon[4357]: [session uid=1000 pid=4357] Successfully activated service 'org.gnome.Shell.HotplugSniffer'
```

**Comment by GlenCooper** [comment]
> > Try disabling animations from the accessibility settings panel
> 
> Good suggestion. Tried that. Still seeing same behavior.

Just adding an update here to say that I've not had any more freezes anymore for quite some time now.  Probably since shortly after my last update.

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
I am still experiencing these issues.  
Disabling animations in accessibility menu did not help.  
The machine started with a Nvidia GPU (1080Ti) and got installed with the NVIDIA ISO.  
The 1080Ti got replaced with a AMD 7900 GRE, and still exhibits the same freezes.   
I do not use Chrome like other comments mentioned, and I use a single display over Displayport now. With the 1080Ti I used the same DP monitor with another HDMI display attached, but not for the whole duration the 1080Ti got used.  
I did not see any relevant system logs so far.  GPU driver seems to behaving properly.

**Comment by jyono** [comment]
happens to me too. i guess we are just supposed to wait for cosmic...

**Comment by BrettFraley** [comment]
I was here Dec 2024 ;)

@joelostblom This ` sudo killall -1 gnome-shell, and then switch back to the graphical login using Ctrl + Alt + F2` saved me about an hour today.

**Comment by BarbzYHOOL** [comment]
Make sure you don't have automated /home backups all the time according to a tutorial, with timeshift-apt

**Comment by lionslair** [comment]
I keep getting the ui locking up for the last few days too. No external monitor connected
