### ISSUE TITLE
[Arch Linux, GNOME 43] Glitches, bad alignment (possible Mutter issue)

### ISSUE THREAD

**Issue by Neo-29** [pop-os/shell#1542]
**(1) Issue/Bug Description:**
Show windows in a good way with no glitch and good alignment

**(2) Steps to reproduce (if you know):**

open any applications in tiling mode

**(3) Expected behavior:**
No glitch good alignment

**(4) Distribution (run `cat /etc/os-release`):**
 
Archlinux up to date

**(5) Gnome Shell version:**

43.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):
 r927.30bf682-1.1

**(7) Where was Pop Shell installed from:**

last commit from chaotic AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1080p

**(9) Other Installed/Enabled Extensions:**
checked without same

**(10) Other Notes:**

**Comment by leviport** [comment]
Could you provide some screenshots?

**Comment by Neo-29** [comment]
I had to remove it.
It was a nightmare.
I'll try later on to post some.
But the glitch can be opening or after.
Hope I can take the screenshot at the good moment

**Comment by keighrim** [comment]
I think I'm experiencing the same issue. I recorded a short screencast showing the glitches
(https://drive.google.com/file/d/1CEIL1doYrjVtnuB-YX0o-l199PThLiq-/view?usp=sharing)
1. windows stop being rendered halfway (nautilus, gvim, gnome-terminal).
2. windows are not clickable on any part of them. 

I found that tiling works as usual for chrome (stable), firefox, intellij IDEs, etc. So it seems that only gnome apps causing the problem (possibly a GTK4 issue?) . I'm also running arch + gnome43 + x11. 

When tiling mode is off, everything works as expected.

**Comment by Neo-29** [comment]
Quite the same for me...
Even worse.
Going floating doesn't solve any issue

**Comment by Neo-29** [comment]
![image](https://user-images.githubusercontent.com/90937180/200409409-008d1a2d-6125-4092-9ca5-92de9b566cb2.png)
![image](https://user-images.githubusercontent.com/90937180/200409559-d5438f03-1770-40e7-b116-34d890e0a901.png)

Here's the result...

Unusable....

it makes the shell freeze by the way.... can´t close any window withe the mouse

**Comment by fabifont** [comment]
Same problem here. Focus on window's elements doesn't work and windows are glitched.

After some testing, seems like that issue is more evident on X11 rather than Wayland.

**Comment by akumaburn** [comment]
I have this same issue; and its unique to pop-shell with Gnome 43 ; prior to the update (with Gnome 42) it didn't occur. It's as if the render pipeline isn't being cleared, like the animation is just stuck and is waiting for a screen refresh. To be clear I'm also running X11 (on AMD Ryzen + Arch Linux).

**Comment by italoghost** [comment]
Experiencing this on a Nvidia + Intel Arch Linux, using x11. On my AMD machine, with Wayland, this is not happening.

**Comment by dylanbmorgan** [comment]
+1 with gnome 43, arch linux, AMD CPU, and nvidia-dkms

**Comment by fabifont** [comment]
I found that [latest mutter update](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2667) is the cause of this problem according to: 
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6054
https://gitlab.gnome.org/GNOME/mutter/-/issues/2498

Temporary fix (downgrade mutter to 43.0): ```sudo pacman -U file:///var/cache/pacman/pkg/mutter-43.0-1-x86_64.pkg.tar.zst```

**Comment by Neo-29** [comment]
> I found that [latest mutter update](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2667) is the cause of this problem according to: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6054 https://gitlab.gnome.org/GNOME/mutter/-/issues/2498
> 
> Temporary fix (downgrade mutter to 43.0): `sudo pacman -U file:///var/cache/pacman/pkg/mutter-43.0-1-x86_64.pkg.tar.zst`

Confirmed working workaround

**Comment by yochananmarqos** [comment]
> I found that [latest mutter update](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2667) is the cause of this problem according to:
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6054

Reverting the commit mentioned in that issue fixes the problem. `mutter` 43.1-1.0 in the Manjaro unstable and testing branches contains the fix.

**Comment by developomp** [comment]
> I found that [latest mutter update](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2667) is the cause of this problem according to: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6054 https://gitlab.gnome.org/GNOME/mutter/-/issues/2498
> 
> Temporary fix (downgrade mutter to 43.0): `sudo pacman -U file:///var/cache/pacman/pkg/mutter-43.0-1-x86_64.pkg.tar.zst`

Alternatively, you can use the following command:
```
sudo pacman -U https://archive.archlinux.org/packages/m/mutter/mutter-43.0-1-x86_64.pkg.tar.zst
```

**Comment by Neo-29** [comment]
This is NOT sufficient here.
I did that but still lots of artefacts and glitches.

**Comment by developomp** [comment]
I've been using mutter 43.0 for the past couple of days and I haven't seen any issues. Also, [I thought it was fixed for you?](https://github.com/pop-os/shell/issues/1542#issuecomment-1308691049)

**Comment by fabifont** [comment]
> This is NOT sufficient here. I did that but still lots of artefacts and glitches.

It is. Please be sure that you downgraded to 43.0 and relogged into your system.

Anyway on Arch Linux it hasn't been fixed yet, so when you perform a system update use `--ignore=mutter` to avoid upgrading to 43.1 again

**Comment by developomp** [comment]
Or you can do this in /etc/pacman.conf
```
IgnorePkg   = mutter
```

**Comment by Neo-29** [comment]
The glitches appears on opening settings... Not always.... Can't even see all the window....
Some like gnome terminal won't fit all the screen.(large gap in the bottom)
I did downgrade I did reboot and I can assure you this is not fixed

**Comment by fabifont** [comment]
> Or you can do this in /etc/pacman.conf
> 
> ```
> IgnorePkg   = mutter
> ```

Yes, but then remember to remove it when it will be patched

**Comment by fabifont** [comment]
> The glitches appears on opening settings... Not always.... Can't even see all the window.... Some like gnome terminal won't fit all the screen.(large gap in the bottom) I did downgrade I did reboot and I can assure you this is not fixed

Can you please provide a screen recording?

**Comment by Neo-29** [comment]
![image](https://user-images.githubusercontent.com/90937180/202912859-06c44e8a-24b0-4eb4-800f-0d40e979c154.png)

**Comment by Neo-29** [comment]
Sometimes it's ok sometimes nope...
A real pain...

**Comment by Neo-29** [comment]
![image](https://user-images.githubusercontent.com/90937180/202913135-86a962bd-8ca5-451e-8350-b41f6668e6c1.png)
look below the terminal...
gap is set correctly to 2
It even does not fit the screen
Even gap 0 still a hole down below the terminal here....
Not with others app >
This does not occur

**Comment by Neo-29** [comment]
![image](https://user-images.githubusercontent.com/90937180/202913452-26dc664e-2166-494f-98cd-803bec2b7e1e.png)
gap doesn´'t work with alacritty full screen too

**Comment by Neo-29** [comment]
Last one 
![image](https://user-images.githubusercontent.com/90937180/202913558-41818ac9-14eb-4555-bbd4-2275c9f0193c.png)

**Comment by fabifont** [comment]
> ![image](https://user-images.githubusercontent.com/90937180/202913135-86a962bd-8ca5-451e-8350-b41f6668e6c1.png) look below the terminal... gap is set correctly to 2 It even does not fit the screen Even gap 0 still a hole down below the terminal here.... Not with others app > This does not occur

Alacritty + gaps = 2

![image](https://user-images.githubusercontent.com/38903806/203066197-a17e5885-2ef2-4172-ac13-41b996d2a78b.png)

Sorry but I can't reproduce your problem

**Comment by Neo-29** [comment]
Strangely enough . It's ok now with `gnome-terminal`
What remains:
- Glitch (slight) opening `nautilus` 
- Show windows title seems not to work correctly  (nothing changes when switching)
- Active border radius does nothing (why I don' t know)

**Comment by mpolidori** [comment]
> I think I'm experiencing the same issue. I recorded a short screencast showing the glitches ([drive.google.com/file/d/1CEIL1doYrjVtnuB-YX0o-l199PThLiq-/view?usp=sharing](https://drive.google.com/file/d/1CEIL1doYrjVtnuB-YX0o-l199PThLiq-/view?usp=sharing))
> 
> 1. windows stop being rendered halfway (nautilus, gvim, gnome-terminal).
> 2. windows are not clickable on any part of them.
> 
> I found that tiling works as usual for chrome (stable), firefox, intellij IDEs, etc. So it seems that only gnome apps causing the problem (possibly a GTK4 issue?) . I'm also running arch + gnome43 + x11.
> 
> When tiling mode is off, everything works as expected.

I was having the same issue with the same combination (Arch, GNOME 43, X11) and I can confirm that downgrading to `mutter 43.0` resolved it. For me, it wasn't just GNOME apps that would break (freezing or not accepting any input) on tiling—Xterm, Konsole, Termite, _and_ GNOME terminal all behaved the same way (which absolutely killed my productivity—luckily the downgrade got me back on track).

**Comment by esauvisky** [comment]
Can confirm, also happens here. Keyboard input reaches the application but mouse clicks don't. Moving the window and forcing it to update makes it work again. 

As mentioned below, downgrading mutter fixed the issue up to an usable state, although there are some minor glitches still.

**Comment by Neo-29** [comment]
Last `mutter` (43.2-1) update gives a slight improvement in behavior.
- still remains glitches (fewer)
-  show active hints doesn't work on all the windows
- show windows title doesn´t  do anything (change)
- active gaps is ok
