### ISSUE TITLE
Outer gaps can be applied multiple times

### ISSUE THREAD

**Issue by leviport** [pop-os/shell#21]
If I go to set an outer gap value of 3 but hit the enter key more than once, the outer gap gets larger with each key press. The number stays the same in the box though, so maybe something just isn't being reset properly when the outer gap value is updated.

**Comment by mmstick** [comment]
This is fixed now

**Comment by brs17** [comment]
This seems to still be an issue. I do not see the issue happen when using an outer gap value of 4, but any other value seems to have this issue.

I am running shell with 8fb6a4d2a0f84acdaf8d04c8cc6d2bcf6331ffd8 as the latest commit.

**Comment by mmstick** [comment]
Seems to be working now with the latest commit

**Comment by LiHRaM** [comment]
This is still an issue for me, am running https://github.com/pop-os/shell/commit/c89282b521c8200a0f858fa1cc4d20523e7e5a00

**Comment by mmstick** [comment]
I see. Only happens if your gap is not a multiple of 4

**Comment by leviport** [comment]
With gaps forced to factors of 4, I think we have this one solved.
