### ISSUE TITLE
Mouse cursor jumping to first open window top left corner after another window is opened

### ISSUE THREAD

**Issue by spxak1** [pop-os/shell#848]
**(1) Issue/Bug Description:**
The mouse pointer location moves to the top left corner of the first opened window, every time a new window is opened. Other combinations of where the mouse pointer moves depending on action. As a result, you launch a new program and it doesn't **steal focus** (focus is on the window the mouse pointer has moved to).

Please watch video here: https://streamable.com/qbnhnd

**(2) Steps to reproduce (if you know):**
* Enable pop-shell extension
* Start with no programs running
* Click Activities
* Select and click a program (from dash or from menu)
* Mouse pointer moves to the top left corner of the window that just opened
* Click Activities
* Select and click another program
* Mouse pointer moves to the top left corner of the first window opened.
* No minimise a window (gnome-tweaks minimise button enabled)
* Select Activities, move pointer to the minimised program, click to open again.
* Mouse pointer moves to the top left corner of that window

**(3) Expected behavior:**
Mouse cursor stays where it was last moved to. Not jumping somewhere else on the screen.

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
```gnome-shell:   Installed: 3.38.2-1pop1~1610298831~20.10~41092e5```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```pop-shell:  Installed: 1.1.0~1611349201~20.10~2b9e4a4```

**(7) Where was Pop Shell installed from:**
```apt upgrade```

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Single 1440p via DP.

**(9) Other Installed/Enabled Extensions:**
None too drastic

**(10) Other Notes:**
* Disabling *tweaks* maximise/minimise buttons makes no difference.
* This seems to be some sort of "left over" from [this issue]( https://github.com/pop-os/shell/pull/843) fixed in the latest pop-shell.
* Disabling pop-shell fixes the issue.
* Launching using keyboard shortcuts works fine (no jumping of pointer).

**Comment by spxak1** [comment]
A further similar behaviour with keyboard shortcuts:

When a window is moved to another workspace ```super+shift+up/down```, the mouse pointer jumps to its top left corner.

Observe: https://streamable.com/c03py0

Thank you.

**Comment by saberstrikez** [comment]
Experiencing similar behavior as @spxak1 has detailed. Directed here by a reddit post and wanted to bring attention to this issue.

**(1) Issue/Bug Description:**

Experiencing similar behavior as @spxak1 has detailed.

Appears the mouse focuses on the next available app after minimizing app tray or closing another app. The behaviour moves the mouse to the top left of the next application.

**(2) Steps to reproduce (if you know):**

- Start with no programs running
- Click Activities
- Select and click a program (from dash or from menu)
- Mouse pointer moves to the top left corner of the window that just opened
- Click Activities
- Select and click another program
- Mouse pointer moves to the top left corner of the first window opened.
- Minimize any app results in the mouse cursor moving to the top left corner of another program.
- Select Activities, move pointer to the minimised program, click to open again.
- Mouse pointer moves to the top left corner of that window


**(3) Expected behavior:**

Mouse should remain where it is/last activity (stationary) with no movement/placement.

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**

GNOME Shell 3.38.2


**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```1.1.0~1611349201~20.10~2b9e4a4```


**(7) Where was Pop Shell installed from:**

apt upgrade


**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1x 1920x1080 @144hz, 1x 1920x1080 @60hz, 1x 1680x1050 @60hz 

**(9) Other Installed/Enabled Extensions:**

- Dash to Dock
- Desktop Icons NG (DING)
- GSConnect
- Pop Shell (DISABLED)



**(10) Other Notes:**

Disabled the Pop Shell Extension resolves the issue.

**Comment by leviport** [comment]
I believe this was solved by https://github.com/pop-os/shell/pull/843, but I can reopen if it still occurs.

**Comment by spxak1** [comment]
This was fixed with the latest update:

~~~
pop-shell:
  Installed: 1.1.0~1611709512~20.10~673b87a
~~~

Many thanks to all you guys.

**Comment by saberstrikez** [comment]
All good now - thank you =)

**Comment by John15321** [comment]
Im encountering the same jumping error even tho my PopShell extension is disabled :thinking:

**Comment by ZaLiTHkA** [comment]
I'm still experiencing this now with `pop-shell` version `1.1.0~1631809642~21.04~5220303`, but I see everyone else here is on POP!_OS `20.10`, whereas I'm on `21.04`.

Is there perhaps a different issue open for this problem?

**Comment by dbetka** [comment]
Problem appear again in version 22.04

**Comment by Pixtriks** [comment]
This problem seems to occur once again in version 22.04

**Comment by cywang117** [comment]
Occurring once again in 22.04 as well. Is there a workaround?

**Comment by n3m0-22** [comment]
I believe this was addressed in https://github.com/pop-os/shell/issues/1488, but if that does not fix the issue you are seeing I'll be happy to look into in.

**Comment by cywang117** [comment]
@n3m0-22 Thanks for getting back to me so quickly. I saw that issue before commenting here, but disabling that active window cursor toggle didn't seem to help. In any case I've downgraded to 20.04 for the time being, so may not be able to provide further debug info. For context, this issue does not appear on my desktop running 22.04, but does appear on an HP Spectre x360 which isn't fully compatible with PopOS, so that may be the issue. I'll comment here if I see it again.

**Comment by n3m0-22** [comment]
@cywang117 Thanks for the info. I have access to an HP ENVY x360. I see if I can reproduce the issue on there.

**Comment by cywang117** [comment]
@n3m0-22 I will try upgrading to 22.04 on the x360 laptop again later this week to see if I can reproduce as well. Thanks again!

**Comment by ayman-mezghani** [comment]
For me it occurs when a window is minimized, then I select it with super+tab, that summons the minimized window and moves my cursor to the top left of that window. Not sure whether this is intended but it would be cool to have a way to disable that.

**Comment by leviport** [comment]
@ayman-mezghani as @n3m0-22 pointed out, this was addressed in #1488.
